CREATE TABLE IF NOT EXISTS content (k VARCHAR(100) PRIMARY KEY, v TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS messages (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150), email VARCHAR(150), phone VARCHAR(30), message TEXT, status VARCHAR(10) DEFAULT 'Pending', reply TEXT, created TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
